"""岗位种子数据与默认演示档案"""

DEFAULT_PROFILE = {
    "student_id": "demo01",
    "name": "李同学",
    "school": "示例大学",
    "grade": "大三",
    "major": "计算机科学与技术",
}

JOBS = [
    {
        "id": "job01",
        "company": "字节跳动",
        "title": "后端开发实习生",
        "industry": "互联网",
        "city": "杭州",
        "type": "暑期实习",
        "pay": "200-300 元/天",
        "tags": ["后端", "转正率高", "租房补贴"],
        "description": "参与核心产品后端服务的设计与开发，负责接口开发、性能优化与线上问题排查。",
        "requirements": ["熟悉 Java/Go，基础扎实", "理解常用中间件与分布式思想", "有实际项目经验优先"],
        "skills": ["Java", "Spring Boot", "MySQL", "Redis", "分布式", "操作系统", "计算机网络"],
    },
    {
        "id": "job02",
        "company": "腾讯",
        "title": "后台开发实习生",
        "industry": "互联网",
        "city": "深圳",
        "type": "日常实习",
        "pay": "150-250 元/天",
        "tags": ["后端", "可转正"],
        "description": "负责后台系统的模块开发与维护，参与海量服务的高可用架构建设。",
        "requirements": ["熟悉 C++ 或 Go", "了解 Linux 与网络编程", "熟悉数据库与缓存原理"],
        "skills": ["C++", "Go", "Linux", "MySQL", "计算机网络", "操作系统"],
    },
    {
        "id": "job03",
        "company": "阿里巴巴",
        "title": "Java 开发实习生",
        "industry": "互联网",
        "city": "上海",
        "type": "暑期实习",
        "pay": "200-350 元/天",
        "tags": ["后端", "内推通道"],
        "description": "参与电商核心链路系统的研发，包括交易、库存、营销等方向的工程落地。",
        "requirements": ["Java 基础扎实", "熟悉 Spring 生态", "了解消息队列与分布式存储"],
        "skills": ["Java", "Spring", "MySQL", "Redis", "Kafka", "分布式"],
    },
    {
        "id": "job04",
        "company": "美团",
        "title": "后端开发实习生",
        "industry": "互联网",
        "city": "北京",
        "type": "日常实习",
        "pay": "180-280 元/天",
        "tags": ["后端", "弹性工作"],
        "description": "参与到店业务后端研发，保障大流量场景下的系统稳定与迭代效率。",
        "requirements": ["熟悉 Java/Spring Boot", "理解高并发场景", "有服务化与缓存使用经验"],
        "skills": ["Java", "Spring Boot", "MySQL", "Redis", "高并发", "分布式"],
    },
    {
        "id": "job05",
        "company": "字节跳动",
        "title": "前端开发实习生",
        "industry": "互联网",
        "city": "北京",
        "type": "暑期实习",
        "pay": "200-300 元/天",
        "tags": ["前端", "转正率高"],
        "description": "参与 Web 与跨端业务开发，负责体验优化与基础组件建设。",
        "requirements": ["掌握 HTML/CSS/JavaScript", "熟悉 Vue 或 React", "了解 HTTP 与工程化"],
        "skills": ["JavaScript", "TypeScript", "Vue", "React", "CSS", "HTTP"],
    },
    {
        "id": "job06",
        "company": "腾讯",
        "title": "产品经理实习生",
        "industry": "互联网",
        "city": "深圳",
        "type": "日常实习",
        "pay": "150-250 元/天",
        "tags": ["产品", "可转正"],
        "description": "负责功能模块的需求分析与产品设计，跟进版本迭代与数据复盘。",
        "requirements": ["有用户研究与需求分析经验", "逻辑清晰、表达能力强", "会使用原型工具与数据分析"],
        "skills": ["用户研究", "需求分析", "数据分析", "Axure", "竞品分析"],
    },
    {
        "id": "job07",
        "company": "阿里巴巴",
        "title": "算法实习生",
        "industry": "互联网",
        "city": "杭州",
        "type": "暑期实习",
        "pay": "250-400 元/天",
        "tags": ["算法", "大模型方向"],
        "description": "参与搜索/推荐/大模型方向的算法研发，负责模型训练与效果优化。",
        "requirements": ["扎实的机器学习与深度学习基础", "熟练使用 Python 与深度学习框架", "数据结构与算法功底好"],
        "skills": ["Python", "PyTorch", "机器学习", "深度学习", "数据结构", "算法"],
    },
    {
        "id": "job08",
        "company": "美团",
        "title": "数据分析实习生",
        "industry": "互联网",
        "city": "上海",
        "type": "日常实习",
        "pay": "180-260 元/天",
        "tags": ["数据", "弹性工作"],
        "description": "支持业务方完成指标体系搭建、异动归因与实验分析，输出数据洞察。",
        "requirements": ["熟练使用 SQL 与 Excel", "掌握 Python 数据分析更佳", "了解 A/B 实验方法论"],
        "skills": ["SQL", "Excel", "Python", "数据分析", "A/B测试", "指标体系"],
    },
    {
        "id": "job09",
        "company": "头部券商",
        "title": "金融科技实习岗",
        "industry": "金融",
        "city": "上海",
        "type": "暑期实习",
        "pay": "200-300 元/天",
        "tags": ["金融科技", "留用考核"],
        "description": "参与量化数据平台与风控系统的数据开发，支持研究员做策略回测。",
        "requirements": ["熟悉 Python 与 SQL", "了解基本金融概念", "数据敏感、细心负责"],
        "skills": ["Python", "SQL", "数据分析", "金融", "量化", "Excel"],
    },
    {
        "id": "job10",
        "company": "头部快消企业",
        "title": "市场部实习生",
        "industry": "快消",
        "city": "上海",
        "type": "日常实习",
        "pay": "150-220 元/天",
        "tags": ["市场", "品牌项目"],
        "description": "协助品牌 campaign 落地，参与市场调研、素材整理与数据复盘。",
        "requirements": ["熟练使用 Office 三件套", "有市场调研或社媒运营经历优先", "沟通表达与执行力强"],
        "skills": ["Excel", "PowerPoint", "市场调研", "数据分析", "沟通表达"],
    },
    {
        "id": "job11",
        "company": "头部车企",
        "title": "智能制造实习生",
        "industry": "制造",
        "city": "广州",
        "type": "暑期实习",
        "pay": "150-220 元/天",
        "tags": ["制造", "工业软件"],
        "description": "参与工厂数据分析与流程优化项目，协助搭建产线数字化看板。",
        "requirements": ["熟悉 Python/SQL", "了解工业工程或项目管理", "能快速学习新业务"],
        "skills": ["Python", "数据分析", "SQL", "工业工程", "项目管理"],
    },
    {
        "id": "job12",
        "company": "头部咨询",
        "title": "咨询助理实习生",
        "industry": "咨询",
        "city": "北京",
        "type": "日常实习",
        "pay": "180-260 元/天",
        "tags": ["咨询", "行业研究"],
        "description": "支持项目组完成行业研究、专家访谈纪要整理与交付物撰写。",
        "requirements": ["结构化思维强", "熟练使用 PPT/Excel", "对行业研究有兴趣"],
        "skills": ["PowerPoint", "Excel", "行业研究", "数据分析", "结构化思维"],
    },
]
