"""结构化种子题库：先保证回答顾问能推荐题目与备考方向，后续再扩展真实题库。"""

QUESTIONS = [
    {
        "id": "q001",
        "company": "字节跳动",
        "direction": "后端",
        "topic": "计算机网络",
        "question": "请完整讲一下 TCP 的三次握手与四次挥手。",
        "reference": "先讲状态迁移，再解释为什么需要三次握手、为什么挥手要四次，最后补一个追问视角：序列号、半关闭、TIME_WAIT。",
        "difficulty": "中等",
    },
    {
        "id": "q002",
        "company": "字节跳动",
        "direction": "后端",
        "topic": "操作系统",
        "question": "进程、线程与协程有什么区别？Java 和 Go 分别怎么用？",
        "reference": "从资源开销、调度单位、切换成本切入，再落到线程池、goroutine 调度与并发编程场景。",
        "difficulty": "中等",
    },
    {
        "id": "q003",
        "company": "阿里巴巴",
        "direction": "后端",
        "topic": "MySQL",
        "question": "MySQL 为什么用 B+ 树做索引？和 B 树、哈希索引相比有什么取舍？",
        "reference": "覆盖磁盘 IO、范围查询、层高与扇出，再说明哈希索引适合等值查询但不适合范围场景。",
        "difficulty": "中等",
    },
    {
        "id": "q004",
        "company": "腾讯",
        "direction": "后端",
        "topic": "Redis",
        "question": "Redis 缓存和数据库一致性怎么做？缓存穿透、击穿、雪崩分别怎么解决？",
        "reference": "先区分三个问题，再分别给布隆过滤器、互斥锁、过期时间与降级方案，最后讨论更新策略。",
        "difficulty": "困难",
    },
    {
        "id": "q005",
        "company": "字节跳动",
        "direction": "算法",
        "topic": "数据结构",
        "question": "实现 LRU 缓存，说明为什么用双向链表 + 哈希表。",
        "reference": "先给 O(1) 读写方案，再解释访问命中后移到队首、淘汰队尾，以及并发场景的优化。",
        "difficulty": "困难",
    },
    {
        "id": "q006",
        "company": "阿里巴巴",
        "direction": "算法",
        "topic": "机器学习",
        "question": "训练集和测试集分布不一致时，模型上线通常会出现什么问题？怎么缓解？",
        "reference": "从过拟合、样本偏差、分布漂移切入，补充数据校验、领域自适应、重采样与监控。",
        "difficulty": "中等",
    },
    {
        "id": "q007",
        "company": "美团",
        "direction": "数据",
        "topic": "业务分析",
        "question": "业务指标出现明显上涨或下跌，你会如何归因？",
        "reference": "先校验口径，再拆维度、分渠道/地域/用户，寻找异常时间段，结合活动、政策与竞品变化给结论。",
        "difficulty": "中等",
    },
    {
        "id": "q008",
        "company": "腾讯",
        "direction": "数据",
        "topic": "SQL",
        "question": "写一条 SQL 计算某产品按天和按渠道的新增用户留存率。",
        "reference": "考察日期表、去重、join 与分母定义，注意留存用户必须是历史新增且当天活跃。",
        "difficulty": "中等",
    },
    {
        "id": "q009",
        "company": "字节跳动",
        "direction": "前端",
        "topic": "浏览器",
        "question": "从输入 URL 到页面渲染，完整过程是什么？哪些环节可以做性能优化？",
        "reference": "按 DNS、TCP/TLS、HTTP、HTML 解析、CSSOM、渲染树、布局绘制梳理，再落到缓存、CDN、资源加载与渲染优化。",
        "difficulty": "中等",
    },
    {
        "id": "q010",
        "company": "腾讯",
        "direction": "产品",
        "topic": "产品思维",
        "question": "如果让你负责微信朋友圈的新入口，你如何做产品判断？",
        "reference": "先定义目标用户和场景，再列需求假设、功能取舍、入口成本、数据指标与灰度方案。",
        "difficulty": "中等",
    },
]
